
import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author nigga
 */
public class InputFrame extends javax.swing.JFrame {
    final String defFirstName = "First Name";
    final String defSecondName = "Last Name";
    final String defDateOfBirth = "DD/MM/YYYY";
    final String defPlaceOfBirth = "Place of Birth";

    /**
     * Creates new form NewJFrame
     */
    public InputFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        rbGroupGender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tfSecondName = new javax.swing.JTextField();
        tfFirstName = new javax.swing.JTextField();
        tfDateOfBirth = new javax.swing.JTextField();
        tfPlaceOfBirth = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        rbMale = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AstroBro");
        setBackground(new Color(0x333333));
        setBounds(new java.awt.Rectangle(0, 0, 640, 480));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(700, 480));
        setMinimumSize(new java.awt.Dimension(700, 480));
        setPreferredSize(new java.awt.Dimension(700, 480));
        setResizable(false);

        jPanel1.setBackground(new Color(0x333333));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(204, 204, 204)));
        jPanel1.setMinimumSize(new java.awt.Dimension(350, 480));
        jPanel1.setPreferredSize(new java.awt.Dimension(350, 480));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ASTROBRO");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setMaximumSize(new java.awt.Dimension(350, 480));
        jLabel1.setMinimumSize(new java.awt.Dimension(350, 480));
        jLabel1.setPreferredSize(new java.awt.Dimension(350, 480));
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new Color(0x333333));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(204, 204, 204)));
        jPanel2.setMaximumSize(new java.awt.Dimension(350, 480));
        jPanel2.setMinimumSize(new java.awt.Dimension(350, 480));
        jPanel2.setPreferredSize(new java.awt.Dimension(350, 480));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        tfSecondName.setBackground(new Color(0x333333));
        tfSecondName.setFont(new java.awt.Font("Bitstream Charter", 0, 13)); // NOI18N
        tfSecondName.setForeground(new Color(204, 204, 204));
        tfSecondName.setText("Last Name");
        tfSecondName.setBorder(null);
        tfSecondName.setCaretColor(new Color(204, 204, 204));
        tfSecondName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfSecondNameMouseClicked(evt);
            }
        });
        tfSecondName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSecondNameActionPerformed(evt);
            }
        });

        tfFirstName.setBackground(new Color(0x333333));
        tfFirstName.setFont(new java.awt.Font("Bitstream Charter", 0, 13)); // NOI18N
        tfFirstName.setForeground(new Color(204, 204, 204));
        tfFirstName.setText("First Name");
        tfFirstName.setBorder(null);
        tfFirstName.setCaretColor(new Color(204, 204, 204));
        tfFirstName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfFirstName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfFirstNameMouseClicked(evt);
            }
        });

        tfDateOfBirth.setBackground(new Color(0x333333));
        tfDateOfBirth.setFont(new java.awt.Font("Bitstream Charter", 0, 13)); // NOI18N
        tfDateOfBirth.setForeground(new Color(204, 204, 204));
        tfDateOfBirth.setText("DD/MM/YYYY");
        tfDateOfBirth.setBorder(null);
        tfDateOfBirth.setCaretColor(new Color(204, 204, 204));
        tfDateOfBirth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfDateOfBirthMouseClicked(evt);
            }
        });

        tfPlaceOfBirth.setBackground(new Color(0x333333));
        tfPlaceOfBirth.setFont(new java.awt.Font("Bitstream Charter", 0, 13)); // NOI18N
        tfPlaceOfBirth.setForeground(new Color(204, 204, 204));
        tfPlaceOfBirth.setText("Place of Birth");
        tfPlaceOfBirth.setBorder(null);
        tfPlaceOfBirth.setCaretColor(new Color(204, 204, 204));
        tfPlaceOfBirth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfPlaceOfBirthMouseClicked(evt);
            }
        });
        tfPlaceOfBirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPlaceOfBirthActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new Color(204, 204, 204));
        jSeparator1.setForeground(new Color(204, 204, 204));

        jSeparator2.setBackground(new Color(204, 204, 204));
        jSeparator2.setForeground(new Color(204, 204, 204));

        jSeparator3.setBackground(new Color(204, 204, 204));
        jSeparator3.setForeground(new Color(204, 204, 204));

        jSeparator4.setBackground(new Color(204, 204, 204));
        jSeparator4.setForeground(new Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Abyssinica SIL", 0, 18)); // NOI18N
        jLabel2.setForeground(new Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html>\n<center>\nWELCOME<br>\nTO<br>\nASTROBRO!<br>\n<center>\n<html>");

        btnOk.setBackground(new Color(0x333333));
        btnOk.setForeground(new Color(204, 204, 204));
        btnOk.setText("OK");
        btnOk.setToolTipText("");
        btnOk.setBorder(new javax.swing.border.LineBorder(new Color(204, 204, 204), 2, true));
        btnOk.setContentAreaFilled(false);

        btnClear.setBackground(new Color(0x333333));
        btnClear.setForeground(new Color(204, 204, 204));
        btnClear.setText("Clear");
        btnClear.setBorder(new javax.swing.border.LineBorder(new Color(204, 204, 204), 2, true));
        btnClear.setContentAreaFilled(false);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        rbGroupGender.add(rbMale);
        rbMale.setForeground(new Color(204, 204, 204));
        rbMale.setText("Male");
        rbMale.setContentAreaFilled(false);

        rbGroupGender.add(jRadioButton1);
        jRadioButton1.setForeground(new Color(204, 204, 204));
        jRadioButton1.setText("Female");
        jRadioButton1.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPlaceOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfSecondName, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbMale)
                                    .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(jRadioButton1))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(tfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(tfSecondName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(tfPlaceOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbMale)
                    .addComponent(jRadioButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClear)
                    .addComponent(btnOk))
                .addGap(124, 124, 124))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void tfSecondNameActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here
        if(evt.getSource() == btnClear) {
            tfFirstName.setText(defFirstName);
            tfSecondName.setText(defSecondName);
            tfDateOfBirth.setText(defDateOfBirth);
            tfPlaceOfBirth.setText(defPlaceOfBirth);
            rbGroupGender.clearSelection();
        }
    }                                        

    private void tfPlaceOfBirthActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void tfFirstNameMouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        if (evt.getSource() == tfFirstName) {
            if(tfFirstName.getText().equals(defFirstName)){
                tfFirstName.setText("");
            }
            if (tfSecondName.getText().isEmpty()) {
                tfSecondName.setText(defSecondName);
            } if (tfDateOfBirth.getText().isEmpty()) {
                tfDateOfBirth.setText(defPlaceOfBirth);
            } if (tfPlaceOfBirth.getText().isEmpty()) {
                tfPlaceOfBirth.setText(defPlaceOfBirth);
            }
        }
    }                                        

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        
    }                                    

    private void tfSecondNameMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
        if (evt.getSource() == tfSecondName) {
            if(tfSecondName.getText().equals(defSecondName)){
                tfSecondName.setText("");
            }
            if (tfFirstName.getText().isEmpty()) {
                tfFirstName.setText(defFirstName);
            } if (tfDateOfBirth.getText().isEmpty()) {
                tfDateOfBirth.setText(defPlaceOfBirth);
            } if (tfPlaceOfBirth.getText().isEmpty()) {
                tfPlaceOfBirth.setText(defPlaceOfBirth);
            }
        }
    }                                         

    private void tfDateOfBirthMouseClicked(java.awt.event.MouseEvent evt) {                                           
        // TODO add your handling code here:
        if (evt.getSource() == tfDateOfBirth) {
            if(tfDateOfBirth.getText().equals(defDateOfBirth)){
                tfDateOfBirth.setText("");
            }
            if (tfFirstName.getText().isEmpty()) {
                tfFirstName.setText(defFirstName);
            } if (tfSecondName.getText().isEmpty()) {
                tfSecondName.setText(defSecondName);
            } if (tfPlaceOfBirth.getText().isEmpty()) {
                tfPlaceOfBirth.setText(defPlaceOfBirth);
            }
        }
    }                                          

    private void tfPlaceOfBirthMouseClicked(java.awt.event.MouseEvent evt) {                                            
        // TODO add your handling code here:
        if (evt.getSource() == tfPlaceOfBirth) {
            if(tfPlaceOfBirth.getText().equals(defPlaceOfBirth)){
                tfPlaceOfBirth.setText("");
            }
            if (tfFirstName.getText().isEmpty()) {
                tfFirstName.setText(defFirstName);
            } if (tfSecondName.getText().isEmpty()) {
                tfSecondName.setText(defSecondName);
            } if (tfDateOfBirth.getText().isEmpty()) {
                tfDateOfBirth.setText(defPlaceOfBirth);
            }
        }
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.ButtonGroup rbGroupGender;
    private javax.swing.JRadioButton rbMale;
    private javax.swing.JTextField tfDateOfBirth;
    private javax.swing.JTextField tfFirstName;
    private javax.swing.JTextField tfPlaceOfBirth;
    private javax.swing.JTextField tfSecondName;
    // End of variables declaration                   
}
