
import java.awt.Color;
import java.awt.Font;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author nigga
 */
public class InputFrame extends javax.swing.JFrame {
    final String defFirstName = "First Name";
    final String defSecondName = "Last Name";
    final String defDateOfBirth = "DD/MM/YYYY";
    final String defPlaceOfBirth = "Place of Birth";
    Font inputFieldFont = new Font("Bitstream Charter", Font.PLAIN, 18);

    /**
     * Creates new form NewJFrame
     */
    public InputFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbGroupGender = new javax.swing.ButtonGroup();
        inputFields = new javax.swing.JPanel();
        tfSecondName = new javax.swing.JTextField();
        tfFirstName = new javax.swing.JTextField();
        tfDateOfBirth = new javax.swing.JTextField();
        tfPlaceOfBirth = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        rbMale = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AstroBro");
        setBackground(new Color(0x333333));
        setBounds(new java.awt.Rectangle(0, 0, 640, 480));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(720, 480));
        setPreferredSize(new java.awt.Dimension(720, 480));
        setResizable(false);
        setSize(new java.awt.Dimension(720, 480));
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        inputFields.setBackground(new Color(0xebe9f7));
        inputFields.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(204, 204, 204)));
        inputFields.setForeground(new Color(0xe9d6fa));
        inputFields.setMaximumSize(new java.awt.Dimension(350, 480));
        inputFields.setMinimumSize(new java.awt.Dimension(350, 480));
        inputFields.setPreferredSize(new java.awt.Dimension(350, 480));
        inputFields.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputFieldsMouseClicked(evt);
            }
        });

        tfSecondName.setBackground(new Color(0xebe9f7));
        tfSecondName.setFont(inputFieldFont);
        tfSecondName.setForeground(new Color(0x100c22));
        tfSecondName.setText("Last Name");
        tfSecondName.setBorder(null);
        tfSecondName.setCaretColor(new Color(204, 204, 204));
        tfSecondName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfSecondNameMouseClicked(evt);
            }
        });
        tfSecondName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSecondNameActionPerformed(evt);
            }
        });

        tfFirstName.setBackground(new Color(0xebe9f7));
        tfFirstName.setFont(inputFieldFont);
        tfFirstName.setForeground(new Color(0x100c22));
        tfFirstName.setText("First Name");
        tfFirstName.setBorder(null);
        tfFirstName.setCaretColor(new Color(204, 204, 204));
        tfFirstName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfFirstName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfFirstNameMouseClicked(evt);
            }
        });

        tfDateOfBirth.setBackground(new Color(0xebe9f7));
        tfDateOfBirth.setFont(inputFieldFont);
        tfDateOfBirth.setForeground(new Color(0x100c22));
        tfDateOfBirth.setText("DD/MM/YYYY");
        tfDateOfBirth.setBorder(null);
        tfDateOfBirth.setCaretColor(new Color(204, 204, 204));
        tfDateOfBirth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfDateOfBirthMouseClicked(evt);
            }
        });

        tfPlaceOfBirth.setBackground(new Color(0xebe9f7));
        tfPlaceOfBirth.setFont(inputFieldFont);
        tfPlaceOfBirth.setForeground(new Color(0x100c22));
        tfPlaceOfBirth.setText("Place of Birth");
        tfPlaceOfBirth.setBorder(null);
        tfPlaceOfBirth.setCaretColor(new Color(204, 204, 204));
        tfPlaceOfBirth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfPlaceOfBirthMouseClicked(evt);
            }
        });
        tfPlaceOfBirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPlaceOfBirthActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new Color(0xebe9f7));
        jSeparator1.setForeground(new Color(204, 204, 204));

        jSeparator2.setBackground(new Color(0xebe9f7));
        jSeparator2.setForeground(new Color(204, 204, 204));

        jSeparator3.setBackground(new Color(0xebe9f7));
        jSeparator3.setForeground(new Color(204, 204, 204));

        jSeparator4.setBackground(new Color(0xebe9f7));
        jSeparator4.setForeground(new Color(204, 204, 204));

        jLabel2.setBackground(new Color(0xebe9f7));
        jLabel2.setFont(new Font("Abyssinica SIL", 0, 24)); // NOI18N
        jLabel2.setForeground(new Color(0x100c22));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/planet.png"))); // NOI18N
        jLabel2.setText("<html>\n<center>\n<strong>ASTROBRO<strong><br>\n<center>\n<html>");

        btnOk.setBackground(new Color(0x726db6));
        btnOk.setFont(inputFieldFont);
        btnOk.setForeground(new Color(0xebe9f7));
        btnOk.setText("OK");
        btnOk.setToolTipText("");
        btnOk.setBorder(new javax.swing.border.LineBorder(new Color(0x726db6), 2, true));
        btnOk.setContentAreaFilled(false);
        btnOk.setOpaque(true);

        btnClear.setBackground(new Color(0x726db6));
        btnClear.setFont(inputFieldFont);
        btnClear.setForeground(new Color(0xebe9f7));
        btnClear.setText("Clear");
        btnClear.setBorder(new javax.swing.border.LineBorder(new Color(0x726db6), 2, true));
        btnClear.setContentAreaFilled(false);
        btnClear.setOpaque(true);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        rbMale.setBackground(new Color(0xebe9f7));
        rbGroupGender.add(rbMale);
        rbMale.setFont(inputFieldFont);
        rbMale.setForeground(new Color(0x100c22));
        rbMale.setText("Male");
        rbMale.setContentAreaFilled(false);

        jRadioButton1.setBackground(new Color(0xebe9f7));
        rbGroupGender.add(jRadioButton1);
        jRadioButton1.setFont(inputFieldFont);
        jRadioButton1.setForeground(new Color(0x100c22));
        jRadioButton1.setText("Female");
        jRadioButton1.setContentAreaFilled(false);

        javax.swing.GroupLayout inputFieldsLayout = new javax.swing.GroupLayout(inputFields);
        inputFields.setLayout(inputFieldsLayout);
        inputFieldsLayout.setHorizontalGroup(
            inputFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputFieldsLayout.createSequentialGroup()
                .addGroup(inputFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputFieldsLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(inputFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPlaceOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfSecondName, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(inputFieldsLayout.createSequentialGroup()
                                .addGroup(inputFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbMale)
                                    .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(inputFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(inputFieldsLayout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(jRadioButton1))
                                    .addGroup(inputFieldsLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(inputFieldsLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        inputFieldsLayout.setVerticalGroup(
            inputFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputFieldsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(tfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(tfSecondName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(tfPlaceOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(inputFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbMale)
                    .addComponent(jRadioButton1))
                .addGap(18, 18, 18)
                .addGroup(inputFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClear)
                    .addComponent(btnOk))
                .addGap(124, 124, 124))
        );

        getContentPane().add(inputFields);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/constellation.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputFieldsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputFieldsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_inputFieldsMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here
        if(evt.getSource() == btnClear) {
            tfFirstName.setText(defFirstName);
            tfSecondName.setText(defSecondName);
            tfDateOfBirth.setText(defDateOfBirth);
            tfPlaceOfBirth.setText(defPlaceOfBirth);
            rbGroupGender.clearSelection();
        }
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == btnOk) {
            String birthdate = tfDateOfBirth.getText();
            Birthday bd = new Birthday(birthdate);
            setVisible(false);
            //new OutputFrame(new Numerology(bd));
        }
    }

    private void tfPlaceOfBirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPlaceOfBirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPlaceOfBirthActionPerformed

    private void tfPlaceOfBirthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfPlaceOfBirthMouseClicked
        // TODO add your handling code here:
        if (evt.getSource() == tfPlaceOfBirth) {
            if(tfPlaceOfBirth.getText().equals(defPlaceOfBirth)){
                tfPlaceOfBirth.setText("");
            }
            if (tfFirstName.getText().isEmpty()) {
                tfFirstName.setText(defFirstName);
            } if (tfSecondName.getText().isEmpty()) {
                tfSecondName.setText(defSecondName);
            } if (tfDateOfBirth.getText().isEmpty()) {
                tfDateOfBirth.setText(defDateOfBirth);
            }
        }
    }//GEN-LAST:event_tfPlaceOfBirthMouseClicked

    private void tfDateOfBirthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfDateOfBirthMouseClicked
        // TODO add your handling code here:
        if (evt.getSource() == tfDateOfBirth) {
            if(tfDateOfBirth.getText().equals(defDateOfBirth)){
                tfDateOfBirth.setText("");
            }
            if (tfFirstName.getText().isEmpty()) {
                tfFirstName.setText(defFirstName);
            } if (tfSecondName.getText().isEmpty()) {
                tfSecondName.setText(defSecondName);
            } if (tfPlaceOfBirth.getText().isEmpty()) {
                tfPlaceOfBirth.setText(defPlaceOfBirth);
            }
        }
    }//GEN-LAST:event_tfDateOfBirthMouseClicked

    private void tfFirstNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfFirstNameMouseClicked
        // TODO add your handling code here:
        if (evt.getSource() == tfFirstName) {
            if(tfFirstName.getText().equals(defFirstName)){
                tfFirstName.setText("");
            } if (tfSecondName.getText().isEmpty()) {
                tfSecondName.setText(defSecondName);
            } if (tfDateOfBirth.getText().isEmpty()) {
                tfDateOfBirth.setText(defDateOfBirth);
            } if (tfPlaceOfBirth.getText().isEmpty()) {
                tfPlaceOfBirth.setText(defPlaceOfBirth);
            }
        }
    }//GEN-LAST:event_tfFirstNameMouseClicked

    private void tfSecondNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSecondNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSecondNameActionPerformed

    private void tfSecondNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfSecondNameMouseClicked
        // TODO add your handling code here:
        if (evt.getSource() == tfSecondName) {
            if(tfSecondName.getText().equals(defSecondName)){
                tfSecondName.setText("");
            }
            if (tfFirstName.getText().isEmpty()) {
                tfFirstName.setText(defFirstName);
            } if (tfDateOfBirth.getText().isEmpty()) {
                tfDateOfBirth.setText(defDateOfBirth);
            } if (tfPlaceOfBirth.getText().isEmpty()) {
                tfPlaceOfBirth.setText(defPlaceOfBirth);
            }
        }
    }//GEN-LAST:event_tfSecondNameMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnOk;
    private javax.swing.JPanel inputFields;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.ButtonGroup rbGroupGender;
    private javax.swing.JRadioButton rbMale;
    private javax.swing.JTextField tfDateOfBirth;
    private javax.swing.JTextField tfFirstName;
    private javax.swing.JTextField tfPlaceOfBirth;
    private javax.swing.JTextField tfSecondName;
    // End of variables declaration//GEN-END:variables
}
